version: 2
project_name: xfconf-profile
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    dir: ./src
    binary: xfconf-profile-linux-amd64

archives: []

# Release configurations
release:
  github:
    owner: winblues
    name: xfconf-profile
  draft: false
  prerelease: false
  name_template: "{{ .ProjectName }}-v{{ .Version }}"
  extra_files:
    - glob: "./**/xfconf-profile-linux-amd64"

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^chore:"
      - "^test:"
