name: Release
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Install goreleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: 'latest'

      - name: Run goreleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Required for GitHub releases
        run: |
          goreleaser release
